#!/usr/bin/bash

echo Building ghl-info...
cc -O2 -Wall -Werror -Wpedantic -o build/ghl-info src/info.c
echo Building ghl-warn...
cc -O2 -Wall -Werror -Wpedantic -o build/ghl-warn src/warn.c
echo Building ghl-ok...
cc -O2 -Wall -Werror -Wpedantic -o build/ghl-ok src/ok.c
echo Building ghl-error...
cc -O2 -Wall -Werror -Wpedantic -o build/ghl-error src/error.c
